version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/quran-0.0.2-SNAPSHOT.jar
  discard-paths: yes