services:
  app:
    build: .
    container_name: quran
    depends_on:
      - db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ahmad2021
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    networks:
      - nat1

  db:
    image: 'postgres:14-alpine'
    container_name: db
    volumes:
      - lib-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ahmad2021
      - POSTGRES_DB=test
    networks:
      - nat1
volumes:
  lib-data:

networks:
  nat1: